### ISSUE TITLE
Issue with wheel.js file

### ISSUE THREAD

**Issue by Tejeswini** [jh3y/wheel#4]
Hi ,

In my application, I am using wheel plugin for customize carousel. And i am trying to import wheel.js .

But i am getting issue stating that, Uncaught TypeError: Cannot read property 'className' of null.

I did not change any code. please help me out.

Thanks in Advcance.

**Comment by jh3y** [comment]
Hi @Tejeswini 

I haven't looked at wheel for some time. However, if you are getting an error whereby the property `className` is null, it would be an issue where the script does not have an element to work with.

Are you passing an element into the constructor and do you have DOM elements in place? Also are you using the right query selector for elements?

@jh3y

**Comment by Tejeswini** [comment]
Thanks for your quick reply.

Yes, i did not pass the correct class name in query selector.

Now i changed and getting new error, require is not defined at
 var wheel = require('wheel');
		var element = document.querySelector('.myWheel');

Thanks for you great help.

**Comment by jh3y** [comment]
No problem!

@jh3y
